export const TOPICS = [
    'Sports',
    'Politics',
    'Technology News',
    'Economy',
    'Culture and Entertainment',
    'Health and Wellness',
    'Environment',
    'Science',
    'Travel and Tourism',
    'Business',
    'Education',
    'Science and Technology',
    'Travel and Tourism',
    'Business',
    'Education',
    'Science and Technology',
    'Travel and Tourism',
  ];
